"""add visit_entities table

Revision ID: 045c55037950
Revises: 65e992a271e0
Create Date: 2026-04-26 19:28:38.431060

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy
from sqlalchemy.dialects import postgresql

revision: str = '045c55037950'
down_revision: Union[str, None] = '65e992a271e0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('visit_entities',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('visit_id', sa.UUID(), nullable=False),
    sa.Column('entity_type', sa.String(length=32), nullable=False),
    sa.Column('entity_text', sa.String(length=500), nullable=False),
    sa.Column('normalized_text', sa.String(length=500), nullable=False),
    sa.Column('negated', sa.Boolean(), nullable=False),
    sa.Column('severity', sa.String(length=32), nullable=True),
    sa.Column('duration', sa.String(length=64), nullable=True),
    sa.Column('char_start', sa.Integer(), nullable=True),
    sa.Column('char_end', sa.Integer(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('extra', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['visit_id'], ['visits.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_visit_entities_entity_type'), 'visit_entities', ['entity_type'], unique=False)
    op.create_index(op.f('ix_visit_entities_normalized_text'), 'visit_entities', ['normalized_text'], unique=False)
    op.create_index(op.f('ix_visit_entities_visit_id'), 'visit_entities', ['visit_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_visit_entities_visit_id'), table_name='visit_entities')
    op.drop_index(op.f('ix_visit_entities_normalized_text'), table_name='visit_entities')
    op.drop_index(op.f('ix_visit_entities_entity_type'), table_name='visit_entities')
    op.drop_table('visit_entities')
    # ### end Alembic commands ###
